<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;

class UsuarioController extends BaseAdminController
{
    protected function prePersistEntity($entity)
    {
        parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

}
